---
name: Scan

on:
  schedule:
    - cron: '*/01 * * * *'

jobs:
  cve-scanner:
    runs-on: ubuntu-latest
    steps:
      - name: Run vulnerability scanner
        uses: aquasecurity/trivy-action@0.0.6
        with:
          image-ref: "nginx:latest"
          format: "table"
          exit-code: "1"
          severity: "CRITICAL"
