name: Test hidden secrets

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Test secrets'
        default: 'master'
        required: true


jobs:
  release:
    steps:
      - name: With secret
        env:
          MYSECRET: ${{ secrets.MYSECRET }}
        run: |
          env

      - name: Without secret
        run: |
          env